spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/db_name
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

